version: '3.7'

services:
 drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

 db:
    images: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
 drupal_data:
 db_data: